### ISSUE TITLE
'ENOENT' loginkeys

### ISSUE THREAD

**Issue by ypc123** [valndev/vaporBooster#22]
it never works, please help

![Screenshot_1](https://github.com/valndev/vaporBooster/assets/10389186/a8eb4576-ba94-4d67-8c12-a3eccf33e5f8)

**Comment by valndev** [comment]
Should be fixed in the latest release, please try it and let me know.

**Comment by ypc123** [comment]
the problem is solved and the steamguard does not ask again, you did it very well

Thanks, if i run into any other problem, i will let you know
